Add modal window
js-tasks-ru/htmlcss-20231027_n-a-kashaeva pull request #14
Opened 2023-11-17 13:19 UTC by kashaeva-dev

2023-11-17 17:22 UTC, kashaeva-dev commented
почему-то появляется скролл, не знаю, как его убрать

2023-11-18 20:57 UTC, GSemikozov commented
> почему-то появляется скролл, не знаю, как его убрать

все ок, это проблема на уровне js скрипта)

2023-11-18 21:00 UTC, GSemikozov requested changes

2023-11-18 21:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +
здесь еще стоит указать фон через grba

2023-11-18 21:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__shadow{
и тогда избавиться от этого ненужного элемента

2023-11-18 21:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    opacity: 1;
кажется лишним

2023-11-18 21:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin-top: 0;
лишнее

2023-11-18 21:00 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
1) кнопки у нас уже есть (подключены в main, общие, как раз чтобы не дублировать везде одни и те же стили), 2) чужие блоки ни в коем случае не описываем здесь 3) да и вообще кнопка это не часть модалки ))

2023-11-20 14:57 UTC, kashaeva-dev commented on 05-lection3/02-modal/modal.css
> +.modal__shadow{
убрала

2023-11-20 14:58 UTC, kashaeva-dev commented on 05-lection3/02-modal/modal.css
> +    opacity: 1;
убрала

2023-11-20 14:58 UTC, kashaeva-dev commented on 05-lection3/02-modal/modal.css
> +    margin-top: 0;
все равно схлопнутся, убрала

2023-11-20 14:58 UTC, kashaeva-dev commented on 05-lection3/02-modal/modal.css
> +.button {
исправила

2023-11-20 15:16 UTC, merged