Add adaptive homepage
js-tasks-ru/htmlcss-20231027_n-a-kashaeva pull request #15
Opened 2023-11-17 21:14 UTC by kashaeva-dev

2023-11-17 21:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-18 21:02 UTC, GSemikozov requested changes

2023-11-18 21:02 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +        <div class="modal" id="modal">
эх, модалка заехала, придется ждать пока замерджим ее, и потом подлить свежий апстрим мастер

2023-11-18 21:02 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <div class="modal__close" id="modal-close"></div>
`<button>`

2023-11-18 21:02 UTC, GSemikozov commented on components/container/container.css
> +    max-width: 344px;
можно оставить 1110 - в этом и прелесть max-width) тогда тогда задать `padding: 0 15px`

2023-11-20 14:25 UTC, kashaeva-dev commented on 05-lection3/02-modal/index.html
> +        <div class="modal" id="modal">
я ветку новую не с мастера сделала, из-за этого?

2023-11-20 15:06 UTC, kashaeva-dev commented on 05-lection3/02-modal/index.html
> +                <div class="modal__close" id="modal-close"></div>
это исправила в модалке

2023-11-20 15:06 UTC, kashaeva-dev commented on components/container/container.css
> +    max-width: 344px;
исправила, стало лучше

2023-11-20 15:16 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +        <div class="modal" id="modal">
ага

2023-11-20 15:17 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <div class="modal__close" id="modal-close"></div>
главное теперь не перезатереть при мердже (мы мерджим этот позже модалки)

2023-11-20 15:17 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <div class="modal__close" id="modal-close"></div>
советую проверить после мерджа

2023-11-20 15:17 UTC, GSemikozov submitted a review, later dismissed

2023-11-20 15:17 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-11-20 15:18 UTC, GSemikozov approved these changes

2023-11-20 15:18 UTC, merged