Add avatar
js-tasks-ru/htmlcss-20231027_n-a-kashaeva pull request #17
Opened 2023-11-23 12:20 UTC by kashaeva-dev

2023-11-23 12:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-23 21:12 UTC, GSemikozov requested changes

2023-11-23 21:12 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +img {
.avatar__img

2023-11-23 21:12 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +img {
.avatar__tag?

2023-11-23 21:12 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    max-width: 100%;
`height 100% + width 100% + object-fit: cover + border-radius: 50% ` именно здесь

2023-11-23 21:12 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: 160 px;
лишний пробел

2023-11-24 19:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-24 19:43 UTC, kashaeva-dev commented on 06-lection4/01-avatar/avatar.css
> +img {
исправила

2023-11-24 19:44 UTC, kashaeva-dev commented on 06-lection4/01-avatar/avatar.css
> +    max-width: 100%;
исправила

2023-11-24 19:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-24 19:44 UTC, kashaeva-dev commented on 06-lection4/01-avatar/avatar.css
> +    width: 160 px;
исправила

2023-11-25 20:53 UTC, GSemikozov approved these changes

2023-11-25 20:53 UTC, merged