Add checkbox
js-tasks-ru/htmlcss-20231027_n-a-kashaeva pull request #21
Opened 2023-11-27 11:12 UTC by kashaeva-dev

2023-11-27 11:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-28 21:01 UTC, GSemikozov requested changes

2023-11-28 21:01 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    stroke-width: 3px;
лишнее (у импортируемой иконки и там все правильно указано)

2023-11-28 21:01 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    color: white;
лишнее

2023-11-28 21:01 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    color: white;
или хотя бы из переменной

2023-11-28 21:01 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:disabled {
это состояние лишнее, нет необходимости дублировать стили

2023-12-01 11:55 UTC, kashaeva-dev commented on 07-lection5/01-checkbox/checkbox.css
> +    stroke-width: 3px;
исправила

2023-12-01 11:55 UTC, kashaeva-dev commented on 07-lection5/01-checkbox/checkbox.css
> +    color: white;
сделала переменной, если уберу, то станет черной, так как у иконки стоит currentColor

2023-12-01 11:56 UTC, kashaeva-dev commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:disabled {
убрала

2023-12-05 20:30 UTC, merged