Add radio buttons
js-tasks-ru/htmlcss-20231027_n-a-kashaeva pull request #22
Opened 2023-11-27 13:22 UTC by kashaeva-dev

2023-11-27 13:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-27 13:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-02 19:37 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    margin: 16px 0px;
вертикальные марджины? точно не надо

2023-12-04 10:01 UTC, kashaeva-dev commented on 07-lection5/02-radio/radio.css
> +    margin: 16px 0px;
переделала

2023-12-05 20:32 UTC, GSemikozov requested changes
конфликт

2023-12-06 21:36 UTC, GSemikozov approved these changes

2023-12-06 21:36 UTC, merged