Add toggler
js-tasks-ru/htmlcss-20231027_n-a-kashaeva pull request #23
Opened 2023-11-27 14:08 UTC by kashaeva-dev

2023-11-27 14:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-27 14:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-02 19:40 UTC, GSemikozov requested changes

2023-12-02 19:40 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    margin: 0px 16px;
лишнее + inline-block

2023-12-02 19:40 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    stroke-width: 3px;
лишнее

2023-12-02 19:40 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__input:disabled {
лишнее

2023-12-02 19:40 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    position: relative;
+ inline-block

2023-12-02 19:40 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    margin: 16px 0px;
лишнее

2023-12-02 19:40 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    left: 5%;
лучше в пикселях, будет надежнее

2023-12-02 19:40 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    transform: translate(-5%, -50%);
и тут по оси х

2023-12-02 19:40 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    left: 95%;
и тут (см выше). Я бы кстати рекомендовал двигать через translateX только

2023-12-04 10:46 UTC, kashaeva-dev commented
Добавила анимацию, но почему-то transition работает у меня только в одну сторону, возвращение к исходному положению делала отдельно, при этом свойства задавать не потребовалось, все стало работать после того, как просто еще раз прописала transition для возвращения к исходному состоянию. Почему у меня так происходит?

2023-12-05 20:34 UTC, GSemikozov commented
> Добавила анимацию, но почему-то transition работает у меня только в одну сторону, возвращение к исходному положению делала отдельно, при этом свойства задавать не потребовалось, все стало работать после того, как просто еще раз прописала transition для возвращения к исходному состоянию. Почему у меня так происходит?

вижу по коду что слишком много там транзишнов навешано. Все можно удалить, задать лишь 1 на уровне класса .toggler__input по умолчанию

2023-12-05 20:34 UTC, GSemikozov requested changes
конфликт

2023-12-05 20:34 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    padding-bottom: 16px;
лишнее

2023-12-06 12:07 UTC, kashaeva-dev commented on 07-lection5/03-toggler/toggler.css
> +    padding-bottom: 16px;
все исправила, transition на классе .toggler__input не работал, сделала по 1 на классах .toggler__control и .toggler__inner, все заработало в обе стороны

2023-12-16 21:30 UTC, GSemikozov approved these changes

2023-12-16 21:31 UTC, merged