Dz7 input
js-tasks-ru/htmlcss-20231027_n-a-kashaeva pull request #24
Opened 2023-11-29 12:34 UTC by kashaeva-dev

2023-11-29 12:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-01 11:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-01 12:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-12-02 19:44 UTC, GSemikozov requested changes

2023-12-02 19:44 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="input">
а вот здесь заворачивать в лейбл не надо

2023-12-02 19:44 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <div class="input__label">Label</div>
вот это и есть лейбл

2023-12-02 19:44 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <input type="text" class="input__field">
чтобы позиционировать иконки только относительно инпута - их дано завернуть в общий враппер с position: relative

2023-12-02 19:44 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="input">
input_success

2023-12-02 19:44 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="input">
input_error

2023-12-02 19:44 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <svg class="input__icon_success input_icon_active">
а как же основной класс элемента к которому применяется модификатор?) input__icon

2023-12-02 19:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    margin: 39px 0px;
однозначно лишнее

2023-12-02 19:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    margin-top: 5px;
марджин на уровне лейбла (потому что лейбл опциональный, его может и не быть, так что лишний марджин нам не нужен)

2023-12-04 12:02 UTC, kashaeva-dev commented on 07-lection5/04-input/index.html
> +            <label class="input">
исправила

2023-12-04 12:06 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +    margin: 39px 0px;
убрала

2023-12-04 12:06 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +    margin-top: 5px;
сделала

2023-12-05 20:38 UTC, GSemikozov requested changes

2023-12-05 20:38 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <div class="input-container">
здесь должен быть класс блока (элементы вне своего блока не могут существовать)

2023-12-05 20:38 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <div class="input__label">Success</div>
каждый инпут - должен быть завернут в отдельный div с классом блока. Ну и лейблы - это `<label>`

2023-12-05 20:38 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    margin-bottom: 16px;
лишнее

2023-12-05 20:38 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    display: inline;
по умолчанию все иконки скрыты, а показываем нужную, привязываясь к глобальному модификатору состояния - `.input_success .input__icon_success { display: inline; }`

2023-12-06 12:24 UTC, kashaeva-dev commented on 07-lection5/04-input/index.html
> +        <div class="input-container">
исправила

2023-12-06 12:24 UTC, kashaeva-dev commented on 07-lection5/04-input/index.html
> +            <div class="input__label">Success</div>
исправила

2023-12-06 12:25 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +    margin-bottom: 16px;
исправила, обернула все инпуты в .input__wrapper, чтобы настроить расстояние между ними в 16px

2023-12-06 21:56 UTC, GSemikozov requested changes
конфликт

2023-12-07 11:09 UTC, kashaeva-dev commented on 07-lection5/04-input/index.html
> +                    <svg class="input__icon input_success input__icon_success">
перенесла, но я не понимаю, зачем вообще нужен input_success, я border-color для input меняю с помощью класса input__field_success, иконку отображаю с помощью input__icon_success, а input_success могу убрать - ничего не изменится

2023-12-07 11:09 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +.input__wrapper {
сделала

2023-12-16 22:09 UTC, GSemikozov requested changes

2023-12-16 22:09 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__wrapper {
вот тут странно, но можно попробовать связать лейблы с инпутами через id и перепроверить. А еще можно отменить автокомплит

2023-12-16 22:09 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    display: inline;
а они не должны делать одно и то же - display: inline; на .input_success и .input_invalid совершенно лишние

2023-12-20 12:09 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +.input__wrapper {
помогло связать лейблы с инпутами

2023-12-20 12:10 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +.input__wrapper {
а вот отмена автокомплита не сработала

2023-12-20 14:07 UTC, kashaeva-dev commented on 07-lection5/04-input/index.html
> +                    <svg class="input__icon input_success input__icon_success">
исправила

2023-12-26 18:01 UTC, GSemikozov requested changes

2023-12-26 18:01 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    display: inline;
вот тут все-таки не исправлено:
если у блока состояние .input_success, то тогда показываем иконку .input__icon_success - `.input_success .input__icon_success { display: inline; }`. Если .input_invalid - то `.input_invalid .input__icon_invalid { display: inline; }`. А по умолчанию, повторюсь, обе иконки `display: none`

2024-01-26 20:39 UTC, kashaeva-dev commented
вроде бы все исправила

2024-01-28 16:44 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                    <svg class="input__icon input_success input__icon_success">
так он задается на уровне блока, и тогда не надо каждому элементу ставить сотню лишних модификаторов которые по сути все относятся к одному и тому же состоянию, в данном случае - success :)

2024-01-28 16:48 UTC, GSemikozov requested changes

2024-01-28 16:48 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                    <svg class="input__icon input_success input__icon_success">
еще раз - на надо создавать модификаторы элементов по типу input__icon_success; надо использовать input_success на уровне блока, и если мы должны изменить отображение элемента - то так: `.input_success .input__icon {}`

2024-01-28 16:48 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_success.input__icon_success {
.input_success .input__icon_success {}
/* здесь input__icon_success нам нужен лишь чтобы показать правильную иконку */

2024-01-28 16:48 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_invalid.input__icon_invalid {
.input_invalid .input__icon_invalid

2024-01-28 16:48 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_success {
.input_success .input__field

2024-01-28 16:48 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_invalid {
.input_invalid .input__field

2024-01-28 20:10 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +.input_success.input__icon_success {
я наконец-то поняла в чем дело! 
исправила

2024-01-28 20:10 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +.input_invalid.input__icon_invalid {
исправила

2024-01-28 20:10 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +.input__field_success {
исправила

2024-01-28 20:10 UTC, kashaeva-dev commented on 07-lection5/04-input/input.css
> +.input__field_invalid {
исправила

2024-01-28 21:06 UTC, GSemikozov approved these changes

2024-01-28 21:07 UTC, merged